name: Mimic
version: '${project.version}'
main: org.grappepie.mimic.Mimic
api-version: '1.20'

commands:
  spawnmimic:
    description: "Spawn a mimic chest."
  mimicdebug:
    description: "Toggle debug mode for mimics."
    usage: /mimicdebug <true|false>
